# Generated by Django 3.2.8 on 2021-11-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normatividad_contable', '0002_alter_respuesta_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='cuestion',
            field=models.TextField(max_length=500, verbose_name='Pregunta'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='contenido',
            field=models.TextField(max_length=500),
        ),
    ]
