# Generated by Django 3.2.8 on 2021-10-15 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areaContableApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='created',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='documento',
        ),
    ]
