# Generated by Django 3.2.8 on 2021-10-15 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areaContableApp', '0002_auto_20211015_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='email',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='password',
        ),
    ]
