# Generated by Django 3.2.8 on 2021-10-16 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areaContableApp', '0004_auto_20211015_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='numero_de_indentidad',
            new_name='numero_de_identidad',
        ),
    ]
