# Generated by Django 3.2.8 on 2021-10-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areaContableApp', '0005_rename_numero_de_indentidad_alumno_numero_de_identidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='numero_de_identidad',
            field=models.IntegerField(unique=True),
        ),
    ]
